export const cityList = [
  { value: '大阪市', furigana: 'おおさかし' },
  { value: '堺市', furigana: 'さかいし' },
  { value: '岸和田市', furigana: 'きしわだし' },
  { value: '豊中市', furigana: 'とよなかし' },
  { value: '池田市', furigana: 'いけだし' },
  { value: '吹田市', furigana: 'すいたし' },
  { value: '泉大津市', furigana: 'いずみおおつし' },
  { value: '高槻市', furigana: 'たかつきし' },
  { value: '貝塚市', furigana: 'かいづかし' },
  { value: '守口市', furigana: 'もりぐちし' },
  { value: '枚方市', furigana: 'ひらかたし' },
  { value: '茨木市', furigana: 'いばらきし' },
  { value: '八尾市', furigana: 'やおし' },
  { value: '泉佐野市', furigana: 'いずみさのし' },
  { value: '富田林市', furigana: 'とんだばやしし' },
  { value: '寝屋川市', furigana: 'ねやがわし' },
  { value: '河内長野市', furigana: 'かわちながのし' },
  { value: '松原市', furigana: 'まつばらし' },
  { value: '大東市', furigana: 'だいとうし' },
  { value: '和泉市', furigana: 'いずみし' },
  { value: '箕面市', furigana: 'みのおし' },
  { value: '柏原市', furigana: 'かしわらし' },
  { value: '羽曳野市', furigana: 'はびきのし' },
  { value: '門真市', furigana: 'かどまし' },
  { value: '摂津市', furigana: 'せっつし' },
  { value: '高石市', furigana: 'たかいしさん' },
  { value: '藤井寺市', furigana: 'ふじいでらし' },
  { value: '東大阪市', furigana: 'ひがしおおさかし' },
  { value: '泉南市', furigana: 'せんなんし' },
  { value: '四條畷市', furigana: 'しじょうなわてし' },
  { value: '交野市', furigana: 'かたのし' },
  { value: '大阪狭山市', furigana: 'おおさかさやまし' },
  { value: '阪南市', furigana: 'はんなんし' },
  { value: '三島郡島本町', furigana: 'みしまぐんしまもとちょう' },
  { value: '豊能郡豊能町', furigana: 'とよのぐんとよのちょう' },
  { value: '豊能郡能勢町', furigana: 'とよのぐんのせちょう' },
  { value: '泉北郡忠岡町', furigana: 'せんぼくぐんただおかちょう' },
  { value: '泉南郡熊取町', furigana: 'せんなんぐんくまたけちょう' },
  { value: '泉南郡田尻町', furigana: 'せんなんぐんたじりちょう' },
  { value: '泉南郡岬町', furigana: 'せんなんぐんみさきちょう' },
  {
    value: '南河内郡太子町',
    furigana: 'みなみかわちぐんたいしちょう',
  },
  {
    value: '南河内郡河南町',
    furigana: 'みなみかわちぐんかなんちょう',
  },
  {
    value: '南河内郡千早赤阪村',
    furigana: 'みなみかわちぐんちはやあかさかむら',
  },
  { value: '神戸市', furigana: 'こうべし' },
  { value: '姫路市', furigana: 'ひめじし' },
  { value: '尼崎市', furigana: 'あまがさきし' },
  { value: '明石市', furigana: 'あかしし' },
  { value: '西宮市', furigana: 'にしのみやし' },
  { value: '洲本市', furigana: 'すもとし' },
  { value: '芦屋市', furigana: 'あしやし' },
  { value: '伊丹市', furigana: 'いたみし' },
  { value: '相生市', furigana: 'あいおいし' },
  { value: '豊岡市', furigana: 'とよおかし' },
  { value: '加古川市', furigana: 'かこがわし' },
  { value: '赤穂市', furigana: 'あこうし' },
  { value: '西脇市', furigana: 'にしわきし' },
  { value: '宝塚市', furigana: 'たからづかし' },
  { value: '三木市', furigana: 'みきし' },
  { value: '高砂市', furigana: 'たかさごし' },
  { value: '川西市', furigana: 'かわにしし' },
  { value: '小野市', furigana: 'おのし' },
  { value: '三田市', furigana: 'さんだし' },
  { value: '加西市', furigana: 'かさいし' },
  { value: '篠山市', furigana: 'ささやまし' },
  { value: '養父市', furigana: 'やぶし' },
  { value: '丹波市', furigana: 'たんばし' },
  { value: '南あわじ市', furigana: 'みなみあわじし' },
  { value: '朝来市', furigana: 'あさごし' },
  { value: '淡路市', furigana: 'あわじし' },
  { value: '宍粟市', furigana: 'ししくし' },
  { value: '加東市', furigana: 'かとうし' },
  { value: 'たつの市', furigana: 'たつのし' },
  { value: '猪名川町', furigana: 'いながわちょう' },
  { value: '多可町', furigana: 'たかちょう' },
  { value: '稲美町', furigana: 'いなみちょう' },
  { value: '播磨町', furigana: 'はりまちょう' },
  { value: '市川町', furigana: 'いちかわちょう' },
  { value: '福崎町', furigana: 'ふくさきちょう' },
  { value: '神河町', furigana: 'かみかわちょう' },
  { value: '太子町', furigana: 'たいしちょう' },
  { value: '上郡町', furigana: 'かみごおりちょう' },
  { value: '佐用町', furigana: 'さようちょう' },
  { value: '香美町', furigana: 'かみちょう' },
  { value: '新温泉町', furigana: 'しんおんせんちょう' },
  { value: '京都市', furigana: 'きょうとし' },
  { value: '福知山市', furigana: 'ふくちやまし' },
  { value: '舞鶴市', furigana: 'まいづるし' },
  { value: '綾部市', furigana: 'あやべし' },
  { value: '宇治市', furigana: 'うじし' },
  { value: '宮津市', furigana: 'みやづし' },
  { value: '亀岡市', furigana: 'かめおかし' },
  { value: '城陽市', furigana: 'じょうようし' },
  { value: '向日市', furigana: 'むこうし' },
  { value: '長岡京市', furigana: 'ながおかきょうし' },
  { value: '八幡市', furigana: 'やわたし' },
  { value: '京田辺市', furigana: 'きょうたなべし' },
  { value: '京丹後市', furigana: 'きょうたんごし' },
  { value: '南丹市', furigana: 'なんたんし' },
  { value: '木津川市', furigana: 'きづがわし' },
  { value: '大山崎町', furigana: 'おおやまざきちょう' },
  { value: '久御山町', furigana: 'くみやまちょう' },
  { value: '井手町', furigana: 'いでちょう' },
  { value: '宇治田原町', furigana: 'うじたわらちょう' },
  { value: '笠置町', furigana: 'かさぎちょう' },
  { value: '和束町', furigana: 'わづかちょう' },
  { value: '精華町', furigana: 'せいかちょう' },
  { value: '南山城村', furigana: 'みなみやましろむら' },
  { value: '京丹波町', furigana: 'きょうたんばちょう' },
  { value: '伊根町', furigana: 'いねちょう' },
  { value: '与謝野町', furigana: 'よさのちょう' },
  { value: '和歌山市', furigana: 'わかやまし' },
  { value: '海南市', furigana: 'かいなんし' },
  { value: '橋本市', furigana: 'はしもとし' },
  { value: '有田市', furigana: 'ありだし' },
  { value: '御坊市', furigana: 'ごぼうし' },
  { value: '田辺市', furigana: 'たなべし' },
  { value: '新宮市', furigana: 'しんぐうし' },
  { value: '紀の川市', furigana: 'きのかわし' },
  { value: '岩出市', furigana: 'いわでし' },
  { value: '紀美野町', furigana: 'きみのちょう' },
  { value: 'かつらぎ町', furigana: 'かつらぎちょう' },
  { value: '九度山町', furigana: 'くどやまちょう' },
  { value: '高野町', furigana: 'こうやちょう' },
  { value: '湯浅町', furigana: 'ゆあさちょう' },
  { value: '広川町', furigana: 'ひろがわちょう' },
  { value: '有田川町', furigana: 'ありだがわちょう' },
  { value: '美浜町', furigana: 'みはまちょう' },
  { value: '日高町', furigana: 'ひだかちょう' },
  { value: '由良町', furigana: 'ゆらちょう' },
  { value: '印南町', furigana: 'いなみちょう' },
  { value: 'みなべ町', furigana: 'みなべちょう' },
  { value: '日高川町', furigana: 'ひだかがわちょう' },
  { value: '白浜町', furigana: 'しらはまちょう' },
  { value: '上富田町', furigana: 'かみとんだちょう' },
  { value: 'すさみ町', furigana: 'すさみちょう' },
  { value: '那智勝浦町', furigana: 'なちかつうらちょう' },
  { value: '太地町', furigana: 'たいじちょう' },
  { value: '古座川町', furigana: 'こざがわちょう' },
  { value: '北山村', furigana: 'きたやまむら' },
  { value: '串本町', furigana: 'くしもとちょう' },
];

export const disabilityTypeList = [
  '知的',
  '精神',
  '身体',
  '知的・精神',
  '知的・身体',
  '精神・身体',
  '知的・精神・身体',
] as const;
